# Generated by Django 3.2.6 on 2021-10-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(max_length=180, verbose_name='Router Name')),
                ('router_status', models.BooleanField(default=True, verbose_name='Status')),
                ('access_id', models.CharField(max_length=200, verbose_name='Access ID')),
                ('access_pwd', models.CharField(max_length=180, verbose_name='Access Password')),
                ('access_url', models.URLField(verbose_name='Access URL')),
                ('brand', models.CharField(max_length=160, verbose_name='Brand')),
                ('firmware', models.CharField(max_length=160, verbose_name='Firmware')),
                ('select_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sites')),
            ],
        ),
    ]
