# Generated by Django 3.2.6 on 2021-11-01 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_routers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterOverviewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.CharField(max_length=100, verbose_name='IP Address')),
                ('curr_datetime', models.DateTimeField(verbose_name='Current Datetime')),
                ('firmware', models.CharField(max_length=160, verbose_name='Firmware Version')),
                ('router_uptime', models.CharField(max_length=200, verbose_name='Router Uptime')),
                ('local_device_time', models.CharField(max_length=200, verbose_name='Local Device Time')),
                ('memoryusage_RAM', models.CharField(max_length=160, verbose_name='RAM Memory Usage')),
                ('memoryusage_Flash', models.CharField(max_length=160, verbose_name='Flash Memory Usage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
